name: reproductor_colaborativo_sw1
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version number for your application
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # iOS style icons support
  lottie: ^2.2.0 # For Lottie animations
  http: ^1.2.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.3
  uni_links: ^0.5.1
  flutter_riverpod: ^2.6.1
  spotify_sdk: ^3.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Linting rules for clean code

flutter:
  # Enables Material Design Icons
  uses-material-design: true

  # Declare assets here
  assets:
    - assets/Lottie/Animation-Login1.json
    - assets/Lottie/Animation-Home.json
    - assets/Lottie/Animation-CrearSala.json
    - assets/Lottie/Animation-joinsala.json
    - assets/Lottie/Animation-RoomPrincipal.json
    - assets/Lottie/Animation-Pulpo.json
    - assets/Lottie/Animation-pulposhark.json
    - assets/Lottie/Animation-connect.json
    - assets/Lottie/Animation -exit.json
    - assets/Lottie/Animation -exit2.json
    - assets/Lottie/Animation -exit3.json
    - assets/Images/bolivia.png





  fonts:
    - family: Starshines
      fonts:
        - asset: assets/Fonts/Starshines.ttf